### ISSUE TITLE
ECDSA Support plan

### ISSUE THREAD

**Issue by prestwich** [near/near-evm#13]
**Problem Statement**
ECRecover is used by DAI, meta transactions, and a number of other interesting/desirable features that delegate access to EVM accounts. We'd like to support it in near-evm in a reasonable way.

However, there doesn't seem to be a good way to handle `ecrecover`, given that Near accounts do not map to secp256k1 keys.

**Goals**
1. Minimal integration work for existing contracts
1. Minimal changes to Parity VM internals
1. Allow near accounts to delegate access
1. Still based on secp256k1 signature recovery (as this is an EVM invariant)

**Proposal**:
1. Create a contract with the [OZ ECDSA](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/cryptography/ECDSA.sol) interface.
    1. this contract accepts signatures and does normal ECDSA recovery, 
    1. The result is used as the key in a `mapping(address => address)`
        1. The key is the pubkeyhash, the value is the near account ID hash
    1. This contract should be a simple fork with <5 added lines of code
1. Expose a new contract method at the NearEVM root `pub fn registerPubkey([u8; 64])`
    1. A near account owner makes a new keypair, and registers it here
    1. the keypair is hashed and truncated (as eth addresses), and used as the key in the address mapping
    1. The predecessor (sender)'s Near Account ID hash (the near account's evm address) is written as the value in the address mapping
    1. This establishes a link between the new ECDSA keypair and the NEAR account
1. Deploy the contract at a known address 
1. publish an NPM package with that address hardcoded in a contract interface.
1. Ideal devex: 
    1. `import {NearECDSA} from "@near/near-ecdsa-sol";`
    1. NearECDSA.recover(...)`

**Comment by prestwich** [comment]
discussion:

should a near account be able to unregister EVM public keys? This breaks some EVM invariants (as EVM accounts can't do that)

allowing unregistration makes it more similar to the NEAR account paradigm

An ECDSAKeypair in `nearlib` and other off-chain libraries would be helpful for future dapp devex

**Comment by prestwich** [comment]
a near account SHOULD be able to register multiple EVM public keys

**Comment by prestwich** [comment]
related #28

**Comment by ilblackdragon** [comment]
Outdated. Added accounts that only exist in EVM.
