### ISSUE TITLE
Add solidity test for self-destruct and recreation at the same address

### ISSUE THREAD

**Issue by prestwich** [near/near-evm#23]
This should be 2 new smart contracts. They should run during the non-RPC tests

Behavior should be as follows:

1. `contract SelfDestruct`
    1. expose a public `selfdestruct` function
2. `contract Deployer`
    1. deploy a SelfDestruct using create2
    2. call its self destruct
    3. require that its `extcodesize` is 0 and its balance is 0
    4. Send money to the address
    5. require that the address balance is correct
    6. deploy a SelfDestruct using create2 to the same address
    7. require that its extcodesize` is non-0. require that balance is same as in step 5

**Comment by ewilz** [comment]
https://github.com/near/near-evm/pull/34
