### ISSUE TITLE
Interpreter deploy_code can silently fail

### ISSUE THREAD

**Issue by prestwich** [near/near-evm#26]
If the constructor of a contract fails to run for any reason (e.g. value on a non-payable constructor), `crate::interpreter::deploy_code` will not deploy the contract code, however, no error will be reported to the user, and the contract address (which is calculated separately) will still be returned by `crate::EvmContract::deploy_code`

Quick fix by adjusting the end of `crate::interpreter::deploy_code` to read as follows

```
    if apply {
        state.commit_changes(&state_updates.unwrap());
        state.set_code(address, &return_data.to_vec());
    } else {
        // TODO: consider whether this should panic.
        panic!(
            format!("Contract failed to deploy, with message: [{}].", 
            hex::encode(&return_data.to_vec()))
        )
    }
```

**Comment by ewilz** [comment]
https://github.com/near/near-evm/pull/29
