### ISSUE TITLE
rpc tests no longer passing

### ISSUE THREAD

**Issue by ewilz** [near/near-evm#45]
I don't believe anything in this repo has changed to make existing rpc tests fail all of a sudden. I believe this may have to do with updates to nearcore that broke compatibility with these rpc tests. the first fail comes when comparing near balances after transferring $near to the evm.

it's helpful to comment out all precompile references so the contract is small enough to deploy and tests can then be run. I comment line 23 in `src/lib.rs` and lines 177-179 in `src/near_ext.rs`

**Comment by ilblackdragon** [comment]
Outdated.
