### ISSUE TITLE
implement blockhash in near_ext

### ISSUE THREAD

**Issue by prestwich** [near/near-evm#6]
The near ext needs to implement a method to serve `block.hash` solidity calls

@ilblackdragon any objections to using `sha256(block_index())`  as suggested in 
https://github.com/nearprotocol/near-bindgen/issues/68 ? It breaks contracts relying on the blockhash instead of a real entropy source.

**Comment by bowenwang1996** [comment]
Does any randomness output suffice? We will soon have randomness beacon.

**Comment by prestwich** [comment]
@bowenwang1996 it's not that we're looking for a source of randomness, it's that the EVM semantics require the blockhash to be available, and some contract designers have (unwisely) used it as a source of randomness. There are legitimate uses of it besides that. So the question is are we comfortable breaking the contracts using it for randomness?

**Comment by bowenwang1996** [comment]
Block hash should not be used for randomness, but it seems that you are suggesting we must expose block hash for evm compatibility. Is that correct?

**Comment by prestwich** [comment]
Yes, the EVM `blockhash` opcode must return _something_. Since Near doesn't expose the blockhash in `env` we could have `blockhash` return a constant (e.g. `[0u8; 32]` or something unique to the block like `sha256(block_index())`

**Comment by bowenwang1996** [comment]
Why do we not expose block hash? @ilblackdragon @evgenykuzyakov @nearmax

**Comment by prestwich** [comment]
I'm fine moving forward with hash of block index. should be really straightforward

**Comment by maxzaver** [comment]
@bowenwang1996 Because there were no real use case. We only expose things when they are requested.
