### ISSUE TITLE
EVM returns unexpected result for ecrecover

### ISSUE THREAD

**Issue by raymondfeng** [near/near-evm#69]
We ran into an issue with NEAR-EVM's ecrecover.

Here is a simple test case extracted from https://github.com/near/near-evm/blob/fe4fcb83b2c5c1176cc7a2e7cd965a7d59b7d8ad/tests/contracts/StandardPrecompiles.sol#L122 to reproduce the issue:

1. Deploy the following contract to NEAR EVM

```solidity
contract TestContract {
  function ecrecovery(bytes32 hash, bytes memory sig)
        public
        pure
        returns (address)
    {
        if (sig.length != 65) return address(0);

        bytes32 r;
        bytes32 s;
        uint8 v;
        assembly {
            r := mload(add(sig, 32))
            s := mload(add(sig, 64))
            v := byte(0, mload(add(sig, 96)))
        }

        address addr = ecrecover(hash, v, r, s);
        return addr;
    }
}
```

2. Use near-web3-provider to call the function

```ts
const addr2 = await contract.methods
      .ecrecovery(
        '0x1111111111111111111111111111111111111111111111111111111111111111',
        '0xb9f0bb08640d3c1c00761cdd0121209268f6fd3816bc98b9e6f3cc77bf82b69812ac7a61788a0fdc0e19180f14c945a8e1088a27d92a74dce81c0981fb6447441b',
      )
      .call();
    console.log('address2', addr2);
```

Please note the hash/sig is copied from https://github.com/near/near-evm/blob/fe4fcb83b2c5c1176cc7a2e7cd965a7d59b7d8ad/tests/contracts/StandardPrecompiles.sol#L26.

## Expected result:

address2 should be  `0x1563915e194D8CfBA1943570603F7606A3115508` 

But `0x0000000000000000000000000000000000000000` is returned instead.

**Comment by artob** [comment]
This repository is obsolete, superseded by [aurora-is-near/aurora-engine](https://github.com/aurora-is-near/aurora-engine) where active development is ongoing. Neither repository, however, is quite ready for users. That said, I'll make sure `ecrecover` works, soonest.

**Comment by artob** [comment]
@raymondfeng Please try the new EVM contract from the [aurora-is-near/aurora-engine](https://github.com/aurora-is-near/aurora-engine) repository. We've fixed `ecrecover` in the commit https://github.com/aurora-is-near/aurora-engine/commit/fc5a73f4e60f638cdedd1fd4175212dfde582be1.
